function setFigureDefaults()
    set(gca,'FontSize',16,'FontName','Arial',...
        'FontWeight','normal','units','centimeters','linewidth',1.5,...
        'YGrid','off','XGrid','off','GridColor',[0.7 0.7 0.7],'box','off')
end
